// src/app/layout.js
import "./globals.css";

export const metadata = {
  title: "NearServe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
